# Generated by Django 5.1.1 on 2024-12-23 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('img_course', models.ImageField(upload_to='images/')),
                ('c_title', models.CharField(max_length=100)),
                ('c_name', models.CharField(max_length=50, unique=True)),
                ('c_branch', models.CharField(max_length=50)),
                ('c_duration', models.CharField(max_length=10)),
                ('c_fee', models.DecimalField(decimal_places=4, max_digits=20)),
                ('c_hostal', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_id', models.CharField(max_length=1000)),
                ('fac_name', models.CharField(max_length=100)),
                ('fac_dep', models.CharField(max_length=100)),
                ('fac_sub', models.CharField(max_length=100)),
                ('fac_profile', models.ImageField(upload_to='')),
                ('fac_exp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SigninModel',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('pas', models.CharField(max_length=10)),
                ('cpas', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_roll', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='media/')),
                ('year', models.IntegerField(default=0)),
                ('mobile', models.IntegerField(unique=True)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.course')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App1.signinmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_dob', models.DateField()),
                ('s_roll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App1.student')),
            ],
        ),
    ]
