# Generated by Django 5.1.1 on 2024-12-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlogin',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='s_roll',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
