# Generated by Django 5.1.1 on 2024-12-24 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_remove_studentlogin_id_alter_studentlogin_s_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlogin',
            name='id',
            field=models.BigAutoField(auto_created=True, default=90, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentlogin',
            name='s_roll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App1.student'),
        ),
    ]
